on: [push, pull_request]
name: Clippy
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libasound2-dev
      - uses: actions/checkout@v2
      - run: rustup show
      - uses: clechasseur/rs-clippy-check@v3
        with:
          args: --all-targets
